name: Run Helix PSI Audit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    
    steps:
      - uses: auniverseaway/helix-actions@main
      - name: Use local PSI action
        working-directory: ./psi
        with:
          psi-key: ${{ secrets.PSI_KEY }}
